apiVersion: v1
version: 2.1.3
appVersion: 2.1.3
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/podinfo
maintainers:
  - email: stefanprodan@users.noreply.github.com
    name: stefanprodan
sources:
  - https://github.com/stefanprodan/podinfo